name             'ansible'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ansible'
long_description 'Installs/Configures ansible'
version          '0.1.0'

depends 's3_file'
depends 'apt'